language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - pip3 install pytest-cov

services:
  - postgresql

env:
  global:
    - APP_SETTINGS="TESTING"

before_script:
  - psql -c 'create database store_manager_testing;' -U postgres
  
# command to run tests
script:
  - python3 -m pytest --cov=app tests/

after_success:
- coveralls