language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

services:
  - postgresql

env:
  global:
    - APP_SETTINGS="TESTING"

before_script:
  - psql -c 'create database store_manager_testing;' -U postgres
  
# command to run tests
script:
  - python -m pytest --cov=app tests/

after_success:
- coveralls